-- Ethiospectrum foundation schema. Apply only with the Supabase CLI or a reviewed migration workflow.
create extension if not exists pgcrypto;
create extension if not exists vector;

create type public.app_role as enum ('member', 'specialist', 'content_editor', 'administrator');
create type public.member_status as enum ('active', 'invited', 'removed');
create type public.permission_level as enum ('owner', 'editor', 'viewer');
create type public.processing_status as enum ('pending', 'processing', 'ready', 'failed', 'deleted');
create type public.resource_status as enum ('draft', 'in_review', 'published', 'archived');

create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end; $$;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, email text not null, first_name text, last_name text, preferred_locale text not null default 'en' check (preferred_locale in ('en','am','es')), timezone text not null default 'UTC', role public.app_role not null default 'member', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create unique index profiles_email_lower_idx on public.profiles (lower(email));
create table public.households (id uuid primary key default gen_random_uuid(), name text not null check (char_length(name) between 1 and 160), primary_owner_id uuid not null references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.household_members (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, relationship text not null check (char_length(relationship) between 1 and 80), permission_level public.permission_level not null default 'viewer', status public.member_status not null default 'invited', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(household_id, user_id));
create table public.dependents (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, first_name text not null, last_name text, preferred_name text, birth_year integer check (birth_year between 1900 and extract(year from now())::integer), school_district text, grade_level text, notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.documents (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, dependent_id uuid references public.dependents(id) on delete set null, uploaded_by uuid not null references public.profiles(id), title text not null, original_filename text not null, storage_path text not null unique, mime_type text not null check (mime_type in ('application/pdf','application/vnd.openxmlformats-officedocument.wordprocessingml.document','text/plain')), file_size bigint not null check (file_size > 0 and file_size <= 52428800), document_type text, detected_language text check (detected_language in ('en','am','es')), processing_status public.processing_status not null default 'pending', created_at timestamptz not null default now(), updated_at timestamptz not null default now(), deleted_at timestamptz);
create table public.document_pages (id uuid primary key default gen_random_uuid(), document_id uuid not null references public.documents(id) on delete cascade, page_number integer not null check (page_number > 0), extracted_text text, extraction_confidence numeric(4,3) check (extraction_confidence between 0 and 1), created_at timestamptz not null default now(), unique(document_id,page_number));
create table public.document_chunks (id uuid primary key default gen_random_uuid(), document_id uuid not null references public.documents(id) on delete cascade, page_number integer not null check (page_number > 0), chunk_index integer not null check (chunk_index >= 0), content text not null, embedding vector(1536), metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now(), unique(document_id,page_number,chunk_index));
create table public.document_analyses (id uuid primary key default gen_random_uuid(), document_id uuid not null references public.documents(id) on delete cascade, analysis_type text not null, language text not null check (language in ('en','am','es')), status public.processing_status not null default 'pending', summary text, structured_result jsonb, model_name text, prompt_version text, created_at timestamptz not null default now());
create table public.conversations (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, dependent_id uuid references public.dependents(id) on delete set null, created_by uuid not null references public.profiles(id), title text, locale text not null default 'en' check (locale in ('en','am','es')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.messages (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations(id) on delete cascade, role text not null check (role in ('user','assistant','system')), content text not null, citations jsonb not null default '[]'::jsonb, model_name text, created_at timestamptz not null default now());
create table public.ai_feedback (id uuid primary key default gen_random_uuid(), message_id uuid not null references public.messages(id) on delete cascade, user_id uuid not null references public.profiles(id), rating smallint not null check (rating between 1 and 5), reason text, comment text, created_at timestamptz not null default now());
create table public.roadmaps (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, dependent_id uuid references public.dependents(id) on delete set null, title text not null, status text not null default 'active' check (status in ('active','archived')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.roadmap_items (id uuid primary key default gen_random_uuid(), roadmap_id uuid not null references public.roadmaps(id) on delete cascade, title text not null, description text, category text, priority text check (priority in ('low','medium','high')), status text not null default 'open' check (status in ('open','in_progress','completed','cancelled')), due_date date, source_type text, source_id uuid, created_at timestamptz not null default now(), completed_at timestamptz);
create table public.reminders (id uuid primary key default gen_random_uuid(), roadmap_item_id uuid not null references public.roadmap_items(id) on delete cascade, user_id uuid not null references public.profiles(id), remind_at timestamptz not null, channel text not null check (channel in ('email','in_app')), status text not null default 'pending' check (status in ('pending','sent','cancelled','failed')), sent_at timestamptz, created_at timestamptz not null default now());
create table public.resources (id uuid primary key default gen_random_uuid(), slug text not null unique, category text not null, status public.resource_status not null default 'draft', author_id uuid references public.profiles(id), published_at timestamptz, reviewed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.resource_translations (id uuid primary key default gen_random_uuid(), resource_id uuid not null references public.resources(id) on delete cascade, locale text not null check (locale in ('en','am','es')), title text not null, summary text not null, body text not null, review_status text not null default 'draft' check (review_status in ('draft','in_review','approved')), reviewed_by uuid references public.profiles(id), created_at timestamptz not null default now(), updated_at timestamptz not null default now(), unique(resource_id,locale));
create table public.specialists (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references public.profiles(id) on delete cascade, bio text, languages text[] not null default '{}', specialties text[] not null default '{}', availability_status text not null default 'unavailable' check (availability_status in ('available','unavailable')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.household_specialists (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, specialist_id uuid not null references public.specialists(id) on delete cascade, assigned_at timestamptz not null default now(), assigned_by uuid references public.profiles(id), status text not null default 'active' check (status in ('active','removed')), unique(household_id,specialist_id));
create table public.support_threads (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, specialist_id uuid references public.specialists(id) on delete set null, status text not null default 'open' check (status in ('open','closed')), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.support_messages (id uuid primary key default gen_random_uuid(), support_thread_id uuid not null references public.support_threads(id) on delete cascade, sender_id uuid not null references public.profiles(id), content text not null, created_at timestamptz not null default now());
create table public.appointments (id uuid primary key default gen_random_uuid(), household_id uuid not null references public.households(id) on delete cascade, specialist_id uuid references public.specialists(id) on delete set null, start_time timestamptz not null, end_time timestamptz not null check (end_time > start_time), meeting_url text, status text not null default 'requested' check (status in ('requested','scheduled','cancelled','completed')), notes text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.consents (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, consent_type text not null, policy_version text not null, accepted_at timestamptz not null default now(), ip_hash text, unique(user_id,consent_type,policy_version));
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id) on delete set null, household_id uuid references public.households(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());

create index household_members_user_idx on public.household_members(user_id) where status = 'active'; create index dependents_household_idx on public.dependents(household_id); create index documents_household_idx on public.documents(household_id) where deleted_at is null; create index document_pages_document_idx on public.document_pages(document_id); create index document_chunks_document_idx on public.document_chunks(document_id); create index conversations_household_idx on public.conversations(household_id); create index roadmaps_household_idx on public.roadmaps(household_id); create index resources_status_idx on public.resources(status); create index audit_logs_household_idx on public.audit_logs(household_id,created_at desc);
create index document_chunks_embedding_idx on public.document_chunks using ivfflat (embedding vector_cosine_ops) with (lists = 100);

do $$ declare r record; begin for r in select tablename from pg_tables where schemaname='public' and tablename in ('profiles','households','household_members','dependents','documents','document_pages','document_chunks','document_analyses','conversations','messages','ai_feedback','roadmaps','roadmap_items','reminders','resources','resource_translations','specialists','household_specialists','support_threads','support_messages','appointments','consents','audit_logs') loop execute format('alter table public.%I enable row level security', r.tablename); end loop; end $$;
do $$
declare
  r record;
begin
  for r in
    select tablename
    from pg_tables
    where schemaname = 'public'
      and tablename in ('profiles', 'households', 'household_members', 'dependents', 'documents', 'conversations', 'roadmaps', 'resources', 'resource_translations', 'specialists', 'support_threads', 'appointments')
  loop
    begin
      execute format(
        'create trigger %I before update on public.%I for each row execute function public.set_updated_at()',
        r.tablename || '_set_updated_at',
        r.tablename
      );
    exception
      when duplicate_object then null;
    end;
  end loop;
end;
$$;
