-- Initial deny-by-default RLS policy layer. Service-role operations must remain server-only.
create or replace function public.is_active_household_member(target_household uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from household_members where household_id=target_household and user_id=auth.uid() and status='active') $$;
create or replace function public.is_assigned_specialist(target_household uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from household_specialists hs join specialists s on s.id=hs.specialist_id where hs.household_id=target_household and hs.status='active' and s.user_id=auth.uid()) $$;
create or replace function public.is_administrator() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from profiles where id=auth.uid() and role='administrator') $$;
create or replace function public.can_access_household(target_household uuid) returns boolean language sql stable security definer set search_path=public as $$ select public.is_active_household_member(target_household) or public.is_assigned_specialist(target_household) or public.is_administrator() $$;

create policy profiles_self on public.profiles for select using (id=auth.uid() or public.is_administrator()); create policy profiles_self_update on public.profiles for update using (id=auth.uid()) with check (id=auth.uid() and role=(select role from public.profiles where id=auth.uid()));
create policy households_access on public.households for select using (public.can_access_household(id));
create policy members_access on public.household_members for select using (public.can_access_household(household_id));
create policy dependents_access on public.dependents for all using (public.can_access_household(household_id)) with check (public.is_active_household_member(household_id));
create policy documents_access on public.documents for select using (public.can_access_household(household_id) and deleted_at is null); create policy documents_member_write on public.documents for insert with check (public.is_active_household_member(household_id) and uploaded_by=auth.uid()); create policy documents_member_update on public.documents for update using (public.is_active_household_member(household_id)) with check (public.is_active_household_member(household_id));
create policy document_pages_access on public.document_pages for select using (exists(select 1 from documents d where d.id=document_id and public.can_access_household(d.household_id) and d.deleted_at is null));
create policy document_chunks_access on public.document_chunks for select using (exists(select 1 from documents d where d.id=document_id and public.can_access_household(d.household_id) and d.deleted_at is null));
create policy analyses_access on public.document_analyses for select using (exists(select 1 from documents d where d.id=document_id and public.can_access_household(d.household_id) and d.deleted_at is null));
create policy conversations_access on public.conversations for all using (public.can_access_household(household_id)) with check (public.is_active_household_member(household_id));
create policy messages_access on public.messages for select using (exists(select 1 from conversations c where c.id=conversation_id and public.can_access_household(c.household_id))); create policy messages_member_write on public.messages for insert with check (exists(select 1 from conversations c where c.id=conversation_id and public.is_active_household_member(c.household_id)));
create policy feedback_self on public.ai_feedback for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy roadmaps_access on public.roadmaps for all using (public.can_access_household(household_id)) with check (public.is_active_household_member(household_id)); create policy roadmap_items_access on public.roadmap_items for all using (exists(select 1 from roadmaps r where r.id=roadmap_id and public.can_access_household(r.household_id))) with check (exists(select 1 from roadmaps r where r.id=roadmap_id and public.is_active_household_member(r.household_id))); create policy reminders_access on public.reminders for all using (user_id=auth.uid()) with check (user_id=auth.uid());
create policy published_resources_read on public.resources for select using (status='published' or public.is_administrator() or exists(select 1 from profiles where id=auth.uid() and role='content_editor')); create policy resource_editor_write on public.resources for all using (public.is_administrator() or exists(select 1 from profiles where id=auth.uid() and role='content_editor')) with check (public.is_administrator() or exists(select 1 from profiles where id=auth.uid() and role='content_editor')); create policy resource_translations_read on public.resource_translations for select using (exists(select 1 from resources r where r.id=resource_id and (r.status='published' or public.is_administrator() or exists(select 1 from profiles where id=auth.uid() and role='content_editor')))); create policy resource_translations_editor_write on public.resource_translations for all using (public.is_administrator() or exists(select 1 from profiles where id=auth.uid() and role='content_editor')) with check (public.is_administrator() or exists(select 1 from profiles where id=auth.uid() and role='content_editor'));
create policy specialists_self_or_admin on public.specialists for select using (user_id=auth.uid() or public.is_administrator()); create policy specialist_assignments_access on public.household_specialists for select using (public.is_active_household_member(household_id) or exists(select 1 from specialists s where s.id=specialist_id and s.user_id=auth.uid()) or public.is_administrator());
create policy support_threads_access on public.support_threads for select using (public.can_access_household(household_id)); create policy support_messages_access on public.support_messages for select using (exists(select 1 from support_threads st where st.id=support_thread_id and public.can_access_household(st.household_id))); create policy appointments_access on public.appointments for select using (public.can_access_household(household_id));
create policy consents_self on public.consents for all using (user_id=auth.uid()) with check (user_id=auth.uid()); create policy audit_logs_admin on public.audit_logs for select using (public.is_administrator());
